trigger:
  - main

resources:
  - repo: self

variables:
  tag: "dot_net_webapp"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push an image
            inputs:
              containerRegistry: 'dckr_rgstr'
              repository: 'test47greatsaev'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(tag)
  - stage: Publish
    displayName: publish
    jobs:
      - job: Publish
        displayName: Publish
        pool:
          vmImage: ubuntu-latest
        steps:        
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Azure subscription 1(93af06e3-69c5-4841-95ad-aa4e171ad538)'
              appName: 'dotNet-sample-webapp'
              containers: 'dot_net_webapp'
