trigger:
  - main

resources:
  - repo: self

variables:
  tag: "dot_net_webapp"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push an image
            inputs:
              containerRegistry: 'dckr_rgstr'
              repository: 'test47greatsaev'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: |
                $(tag)
  - stage: Publish
    displayName: publish
    jobs:
      - job: deploy
        displayName: Prepare env
        pool: 
          vmImage: ubuntu-latest
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Create app service plan
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure subscription 1(93af06e3-69c5-4841-95ad-aa4e171ad538)'
              subscriptionId: '93af06e3-69c5-4841-95ad-aa4e171ad538'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'dotNet-sample-webapp'
              location: 'Italy North'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/arm_templates/app_service_plan.json'
              deploymentMode: 'Incremental'
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Create app service
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure subscription 1(93af06e3-69c5-4841-95ad-aa4e171ad538)'
              subscriptionId: '93af06e3-69c5-4841-95ad-aa4e171ad538'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'dotNet-sample-webapp'
              location: 'Italy North'
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/arm_templates/app_services.json'
              overrideParameters: '-name dotNet-sample-webapp -linuxFxVersion "DOCKER|test47greatsaev.azurecr.io/test47greatsaev:dot_net_webapp" -location "Italy North" -subscriptionId "93af06e3-69c5-4841-95ad-aa4e171ad538"
              -resourceGroupName "dotNet-sample-webapp" -serverFarmResourceGroup "dotNet-sample-webapp" -hostingPlanName "dotNet-sample-webapp-asp"'
              deploymentMode: 'Incremental'
      - job: Publish
        dependsOn: deploy
        displayName: Publish
        pool:
          vmImage: ubuntu-latest
        steps:        
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Azure subscription 1(93af06e3-69c5-4841-95ad-aa4e171ad538)'
              appName: 'dotNet-sample-webapp'
              containers: 'test47greatsaev.azurecr.io/test47greatsaev:dot_net_webapp'
              containerCommand: 'dotnet Tailspin.SpaceGame.Web.dll'
